Skip to content
DEV Community

Log in
Create account


21
Add reaction


0
Jump to Comments


19
Save

Cover image for How to deploy an Astro site to GitHub Pages
GitHub profile image Riz√®l Scarlett
Riz√®l Scarlett for GitHub
Posted on Aug 11, 2022 ‚Ä¢ Updated on Aug 15, 2022

19

2
How to deploy an Astro site to GitHub Pages
#
github
#
tutorial
#
astro
#
react
GitHub Pages on Actions (4 Part Series)
1
Create a No-Touch QR Code Menu with GitHub Pages
2
How to host your first site for free on GitHub Pages
3
How to host a Hugo or Next.js site on GitHub Pages
4
How to deploy an Astro site to GitHub Pages
GitHub Pages now uses customizable GitHub Action workflows to build and deploy your code so that developers can control their authoring framework and deployment. GitHub Pages is a powerful option for storing static content for the following reasons:

It‚Äôs free.
It makes collaboration easy. Anyone can open a pull request to update the site.
Your repository syncs with any changes you made to your site.
While GitHub Pages comes with a default domain name like, https://YOUR_USER_NAME.github.io/ , it supports custom domains.
It uses customizable GitHub Action workflows for builds and deployments.
The team at GitHub made a few starter workflows available to you, so you don‚Äôt have to write them from scratch, and you can use them as examples to support deployments in other frameworks. Currently there are starter workflows for Next.js, Nuxt.js, Gatsby, Hugo, Jekyll, and HTML.

Let‚Äôs learn how to host static sites built with Astro or any workflow of your choice on GitHub Pages!

Please note that your repository must be public to publish your site on GitHub Pages.

After you write your code (using a framework or static generator of your choice) and store it in a repository, go to the settings tab for that repository.

Image description

Click Pages on the left sidebar

Image description

Under build and deployment, choose GitHub Actions

Image description

Create a folder at the root of your project called .github/workflows

Image description

Inside of your .github/workflows folder, create a customized workflow to deploy your specified framework to GitHub Pages (see examples in the section below):

Example workflow for Astro

name: Deploy Astro to GitHub Pages

    on:
     # Trigger the workflow every time you push to the `main` branch
      push:
        branches: [ main ]
      # Allows you to run this workflow manually from the Actions tab on GitHub.
      workflow_dispatch:

      # Allow this job to clone the repo and create a page deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out your repository using git
          uses: actions/checkout@v2

        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: 'npm'

        # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
        - name: Install dependencies
          run: npm ci

        # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
        - name: Build Astro
          run: npm run build --if-present

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ./dist

      deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1

Example workflow for React

    name: Deploy to React GitHub Pages

    on:
     # Trigger the workflow every time you push to the `main` branch
      push:
        branches: [ main ]
      # Allows you to run this workflow manually from the Actions tab on GitHub.
      workflow_dispatch:

      # Allow this job to clone the repo and create a page deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out your repository using git
          uses: actions/checkout@v2

        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: 'npm'

        # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
        - name: Install dependencies
          run: npm ci

        # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
        - name: Build React
          run: npm run build --if-present

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ./build

      deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
Example template for any static generator of your choice

    name: Deploy to ‚Äúyour frameworks‚Äù GitHub Pages

    on:
     # Trigger the workflow every time you push to the `main` branch
      push:
        branches: [ main ]
      # Allows you to run this workflow manually from the Actions tab on GitHub.
      workflow_dispatch:

      # Allow this job to clone the repo and create a page deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out your repository using git
          uses: actions/checkout@v2

        - name: Use ‚ÄúREPLACE WITH THE RUNTIME OF YOUR CHOICE‚Äù
          uses: ‚ÄúREPLACE WITH THE ACTION THAT SETS UP THE RUN TIME OF YOUR CHOICE‚Äù

        # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
        - name: Install dependencies
          run: ‚ÄúREPLACE WITH COMMANDS TO INSTALL DEPENDENCIES‚Äù

        # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
        - name: Build ‚ÄúYOUR STATIC GENERATOR HERE‚Äù
          run: ‚ÄúREPLACE WITH YOUR BUILD COMMAND‚Äù

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ‚ÄúREPLACE WITH YOUR BUILD OUTPUT FOLDER‚Äù

      deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
Within a few seconds, your Action will start running. It will generate a URL and deploy your static site to GitHub Pages if successful.

Image description

Head over to your URL named yourusername.github.io/your_repo_name to check out your live website!

Image description

Gotchas: handling asset paths
When I first published my site on GitHub Pages, I was confused and surprised that I couldn‚Äôt see any images or PDFs even though they were present when I locally hosted the site. This happened because GitHub Pages handles paths differently.

For example, if I have PDF living in this relative path: assets/pdfs/menu-food.pdf, then once hosted on GitHub Pages, update the new path to {‚ÄúREPOSITORY NAME‚Äù}/assets/pdfs/menu-food.pdf

Example
Here's an example repository I built using this method

GitHub logo blackgirlbytes / blackgyalbites-astro

no touch restaurant menu template hosted on GitHub Pages
blackgyalbites

Template for No-touch Menus and Host Static Pages Built with Any Framework on GitHub Pages
screenshot of website with 3 buttons that read: food menu, drinks menu, and catering menu. on the right of it is a screenshot of the drinks menu

Website built with Astro to display restaurant menus when users scan a QR code.

Powered By GitHub Pages
This is a demonstration to show developers that they can build and host static websites using any framework. See more example frameworks hosted on GitHub Pages:

HTML and CSS
Next.js and Tailwind CSS
Astro
Link to live site: https://blackgirlbytes.github.io/blackgyalbites-astro/

Design and Development

All designs and elements are open source, available for free for anyone to use.

Owned by Rizel Scarlett (@blackgirlbytes)

Designed by The Holistic Technologist

Illustrations by Cuoc Doi Prints

Feel free to fork, copy, tweak, and use for any purpose. This project is completely open source, and under MIT license.

Menu Design Template: Canva

Download Assets & Design Elements: Google Drive

blackgirlbytes logo
View on GitHub
Learn more
Watch this talk delivered by Tommy Byrd on Using GitHub Pages with Actions to deploy Hugo sites in seconds
The repository and ReadMe for Deploy Pages
GitHub‚Äôs changelog announcement
Official GitHub Blog Post


Watch this awesome YouTube short by Kedasha demonstrating how to use a customized workflow to deploy a static site generator to GitHub Pages!

I'd love your thoughts on the new customized workflows to deploy to GitHub Pages. Comment below! For more content like this, follow GitHub and me on DEV!
GitHub Pages on Actions (4 Part Series)
1
Create a No-Touch QR Code Menu with GitHub Pages
2
How to host your first site for free on GitHub Pages
3
How to host a Hugo or Next.js site on GitHub Pages
4
How to deploy an Astro site to GitHub Pages
Top comments (0)

Subscribe
pic

Code of Conduct ‚Ä¢ Report abuse
DEV Community

Trending in React
The React community is currently discussing efficient design patterns such as useMemo, useCallback, and useRef to prevent unnecessary component re-rendering. Additionally, there's interest in leveraging AI for full-stack React & Node.js codebase generation.

 anuradha9712 
React Design Patterns
Anuradha Aggarwal „Éª Jul 9
#react #webdev #designpatterns #beginners
 lakshmananarumugam 
15 Advanced TypeScript Tips for Development
Lakshmanan Arumugam „Éª Jul 14
#typescript #react #javascript
 Wasp  
GPT Web App Generator - Let AI create a full-stack React & Node.js codebase based on your description ü§ñü§Ø
Matija Sosic for Wasp „Éª Jul 11
#javascript #webdev #gpt3 #react
 femi_dev 
How to Prevent Unnecessary React Component Re-Rendering
Femi Akinyemi „Éª Jul 8
#react #javascript #performance #frontend
 francescoxx 
Typescript üü¶ CRUD API: Next.js, Tailwind, tRPC, Prisma Postgres, Docker
Francesco Ciulla „Éª Jul 4
#typescript #react #nextjs #webdev
Read next
pavanbelagatti profile image
Demystifying Application Tracing with OpenTelemetry & Jaeger
Pavan Belagatti - Jun 29
fibonacid profile image
RSC and the Echo of 'Presentational and Container Components'
Lorenzo Rivosecchi - Jun 29
akashpattnaik profile image
10 Secret Tips That Make You a Better Python Programmer üòéüíª
Akash Pattnaik - Jun 28
rajaniraiyn profile image
Introducing Continuum Design System: A Modern and Modular UI Framework for Web Development
Rajaniraiyn R - Jul 15

GitHub
Follow
Let's build from here_
More from GitHub
Explorando as APIs do GitHub para automa√ß√£o e integra√ß√£o
#braziliandevs #githubbrasi #github #productivity
GitHub Copilot: Un A√±o Revolucionando la IA
#webdev #github #spanish #ai
How to build a markdown editor in two minutes (with GitHub Copilot)
#ai #githubcopilot #github #tutorial
DEV Community

OpenAI

The most important ChatGPT tutorials live on DEV
Create a DEV account and follow tags such as #openai, #gpt3, #chatgpt, and more

New content every day.
    name: Deploy to React GitHub Pages

    on:
     # Trigger the workflow every time you push to the `main` branch
      push:
        branches: [ main ]
      # Allows you to run this workflow manually from the Actions tab on GitHub.
      workflow_dispatch:

      # Allow this job to clone the repo and create a page deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Check out your repository using git
          uses: actions/checkout@v2

        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: 'npm'

        # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
        - name: Install dependencies
          run: npm ci

        # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
        - name: Build React
          run: npm run build --if-present

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ./build

      deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
DEV Community ‚Äî A constructive and inclusive social network for software developers. With you every step of your journey.
Home
Reading List
Listings
Podcasts
Videos
Tags
FAQ
Forem Shop
Sponsors
About
Contact
Guides
Software comparisons
Code of Conduct
Privacy Policy
Terms of use
Built on Forem ‚Äî the open source software that powers DEV and other inclusive communities.
Made with love and Ruby on Rails. DEV Community ¬© 2016 - 2023.
